### ISSUE TITLE
async Tcp vs basic Tcp

### ISSUE THREAD

**Issue by arash9900** [dmccuskey/dmc-sockets#2]
Hi,
first thanks for your great library.
I want to use websocket in corona sdk for a real-time game.and i do not know
what is the difference of async and basic tcp.
Is async tcp used to avoid blocking user interface?

**Comment by dmccuskey** [comment]
yes, async will avoid blocking the user interface.

technically the basic Lua socket library can be configured to block or not, but it's not "callback-friendly". this library wraps the basic socket lib to give it a "callback-friendly" interface.
